version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: my-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - storage

  storage:
    image: minio/minio
    container_name: my-storage
    volumes:
      - ./storage:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=${SPACES_KEY}
      - MINIO_ROOT_PASSWORD=${SPACES_SECRET}
    command: server /data --console-address ":9001"

volumes:
  storage:
